FROM zeddee/toolbox:latest

USER root

RUN apt-get update -y && apt-get install -y \
  python3 \
  python3-pip \
  python3-venv \
  && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
RUN chown -R data: /opt/venv
  
USER data

ENTRYPOINT . /opt/venv/bin/activate && zsh

